_GENERAL_PRODUCT_GUIDANCE_TERMS = (
    "tpe",
    "silicone",
    "soft vinyl",
    "consumer product",
    "product care",
    "care",
    "clean",
    "cleaning",
    "wash",
    "washing",
    "maintain",
    "maintenance",
    "storage",
    "store it",
    "drying",
    "material",
    "保养",
    "清洁",
    "清洗",
    "存放",
    "收纳",
    "保存",
    "晾干",
    "干燥",
    "材质",
    "商品",
    "製品",
    "お手入れ",
    "洗浄",
    "保管",
    "관리",
    "세척",
    "보관",
    "pflege",
    "reinigen",
    "reinigung",
    "aufbewahrung",
    "cuidado",
    "limpiar",
    "limpieza",
    "guardar",
    "entretien",
    "nettoyer",
    "nettoyage",
    "rangement",
    "cuidados",
    "limpeza",
    "armazenamento",
)

_EVIDENCE_REQUIRED_TERMS = (
    "price",
    "cost",
    "stock",
    "available",
    "availability",
    "shipping",
    "delivery",
    "refund",
    "return policy",
    "warranty",
    "discount",
    "coupon",
    "payment",
    "tracking",
    "order status",
    "多少钱",
    "价格",
    "售价",
    "现货",
    "库存",
    "配送",
    "发货",
    "物流",
    "退款",
    "退货",
    "保修",
    "折扣",
    "优惠券",
    "支付",
    "订单",
    "在庫",
    "価格",
    "配送",
    "返金",
    "garantie",
    "versand",
    "lieferung",
    "precio",
    "envío",
    "livraison",
)

_REGULATED_OR_HIGH_STAKES_TERMS = (
    "legal",
    "illegal",
    "law",
    "medical",
    "doctor",
    "allergy",
    "allergic",
    "toxic",
    "toxicity",
    "guaranteed safe",
    "合法",
    "违法",
    "法律",
    "医疗",
    "医生",
    "过敏",
    "有毒",
    "无毒",
    "绝对安全",
    "未成年人",
    "未成年",
    "minor",
    "underage",
    "child",
    "coercion",
    "forced",
    "non-consensual",
    "強制",
    "違法",
    "medizinisch",
    "gesetzlich",
)


def allows_general_product_guidance(message: str) -> bool:
    normalized = " ".join(message.casefold().split())
    if not normalized:
        return False
    if any(term in normalized for term in _EVIDENCE_REQUIRED_TERMS):
        return False
    if any(term in normalized for term in _REGULATED_OR_HIGH_STAKES_TERMS):
        return False
    return any(term in normalized for term in _GENERAL_PRODUCT_GUIDANCE_TERMS)
