"""add knowledge links and chunk manifests

Revision ID: a5bdb12a805c
Revises: eb0c1eb99480
Create Date: 2026-07-15 01:46:54.138938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5bdb12a805c'
down_revision: Union[str, None] = 'eb0c1eb99480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunk_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'version_id'], ['knowledge_document_versions.tenant_id', 'knowledge_document_versions.version_id'], name=op.f('fk_knowledge_chunk_manifests_tenant_id_version_id_knowledge_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunk_manifests')),
    sa.UniqueConstraint('tenant_id', 'chunk_id', name=op.f('uq_knowledge_chunk_manifests_tenant_id_chunk_id'))
    )
    op.create_index(op.f('ix_knowledge_chunk_manifests_chunk_id'), 'knowledge_chunk_manifests', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_manifests_document_id'), 'knowledge_chunk_manifests', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_manifests_status'), 'knowledge_chunk_manifests', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_manifests_tenant_id'), 'knowledge_chunk_manifests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_manifests_version_id'), 'knowledge_chunk_manifests', ['version_id'], unique=False)
    op.create_table('knowledge_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('link_id', sa.String(length=100), nullable=False),
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.String(length=100), nullable=False),
    sa.Column('target_reference', sa.String(length=500), nullable=False),
    sa.Column('resolved_document_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'version_id'], ['knowledge_document_versions.tenant_id', 'knowledge_document_versions.version_id'], name=op.f('fk_knowledge_links_tenant_id_version_id_knowledge_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_links')),
    sa.UniqueConstraint('tenant_id', 'link_id', name=op.f('uq_knowledge_links_tenant_id_link_id'))
    )
    op.create_index(op.f('ix_knowledge_links_link_id'), 'knowledge_links', ['link_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_source_document_id'), 'knowledge_links', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_tenant_id'), 'knowledge_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_version_id'), 'knowledge_links', ['version_id'], unique=False)
    op.add_column('knowledge_document_versions', sa.Column('index_status', sa.String(length=30), server_default='pending', nullable=False))
    op.create_index(op.f('ix_knowledge_document_versions_index_status'), 'knowledge_document_versions', ['index_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_document_versions_index_status'), table_name='knowledge_document_versions')
    op.drop_column('knowledge_document_versions', 'index_status')
    op.drop_index(op.f('ix_knowledge_links_version_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_tenant_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_source_document_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_link_id'), table_name='knowledge_links')
    op.drop_table('knowledge_links')
    op.drop_index(op.f('ix_knowledge_chunk_manifests_version_id'), table_name='knowledge_chunk_manifests')
    op.drop_index(op.f('ix_knowledge_chunk_manifests_tenant_id'), table_name='knowledge_chunk_manifests')
    op.drop_index(op.f('ix_knowledge_chunk_manifests_status'), table_name='knowledge_chunk_manifests')
    op.drop_index(op.f('ix_knowledge_chunk_manifests_document_id'), table_name='knowledge_chunk_manifests')
    op.drop_index(op.f('ix_knowledge_chunk_manifests_chunk_id'), table_name='knowledge_chunk_manifests')
    op.drop_table('knowledge_chunk_manifests')
    # ### end Alembic commands ###