"""add mvp control plane tables

Revision ID: eb0c1eb99480
Revises: 0001
Create Date: 2026-07-15 01:24:24.514676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb0c1eb99480'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_subject_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('tenant_id', 'event_id', name=op.f('uq_audit_events_tenant_id_event_id'))
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_trace_id'), 'audit_events', ['trace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('tenant_id', 'conversation_id', name=op.f('uq_conversations_tenant_id_conversation_id'))
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('handoff_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('handoff_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('verified_evidence', sa.JSON(), nullable=False),
    sa.Column('failed_tools', sa.JSON(), nullable=False),
    sa.Column('knowledge_sources', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('sla_policy_version', sa.String(length=100), nullable=True),
    sa.Column('expected_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoff_requests')),
    sa.UniqueConstraint('tenant_id', 'handoff_id', name=op.f('uq_handoff_requests_tenant_id_handoff_id')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_handoff_requests_tenant_id_idempotency_key'))
    )
    op.create_index(op.f('ix_handoff_requests_conversation_id'), 'handoff_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_created_at'), 'handoff_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_handoff_requests_customer_id'), 'handoff_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_handoff_id'), 'handoff_requests', ['handoff_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_reason_code'), 'handoff_requests', ['reason_code'], unique=False)
    op.create_index(op.f('ix_handoff_requests_status'), 'handoff_requests', ['status'], unique=False)
    op.create_index(op.f('ix_handoff_requests_tenant_id'), 'handoff_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_trace_id'), 'handoff_requests', ['trace_id'], unique=False)
    op.create_table('knowledge_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('conflict_id', sa.String(length=100), nullable=False),
    sa.Column('conflict_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=500), nullable=False),
    sa.Column('affected_version_ids', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_conflicts')),
    sa.UniqueConstraint('tenant_id', 'conflict_fingerprint', name=op.f('uq_knowledge_conflicts_tenant_id_conflict_fingerprint')),
    sa.UniqueConstraint('tenant_id', 'conflict_id', name=op.f('uq_knowledge_conflicts_tenant_id_conflict_id'))
    )
    op.create_index(op.f('ix_knowledge_conflicts_conflict_id'), 'knowledge_conflicts', ['conflict_id'], unique=False)
    op.create_index(op.f('ix_knowledge_conflicts_status'), 'knowledge_conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_conflicts_tenant_id'), 'knowledge_conflicts', ['tenant_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('tenant_id', 'document_id', name=op.f('uq_knowledge_documents_tenant_id_document_id'))
    )
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.create_table('knowledge_sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('sync_job_id', sa.String(length=100), nullable=False),
    sa.Column('vault_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sync_jobs')),
    sa.UniqueConstraint('tenant_id', 'sync_job_id', name=op.f('uq_knowledge_sync_jobs_tenant_id_sync_job_id'))
    )
    op.create_index(op.f('ix_knowledge_sync_jobs_status'), 'knowledge_sync_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_sync_jobs_sync_job_id'), 'knowledge_sync_jobs', ['sync_job_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sync_jobs_tenant_id'), 'knowledge_sync_jobs', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('tenant_id', 'order_id', name=op.f('uq_orders_tenant_id_order_id'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets')),
    sa.UniqueConstraint('tenant_id', 'ticket_id', name=op.f('uq_support_tickets_tenant_id_ticket_id'))
    )
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_tenant_id'), 'support_tickets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_id'), 'support_tickets', ['ticket_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_kind', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['conversations.tenant_id', 'conversations.conversation_id'], name=op.f('fk_agent_runs_tenant_id_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('tenant_id', 'run_id', name=op.f('uq_agent_runs_tenant_id_run_id')),
    sa.UniqueConstraint('tenant_id', 'trace_id', name=op.f('uq_agent_runs_tenant_id_trace_id'))
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_trace_id'), 'agent_runs', ['trace_id'], unique=False)
    op.create_table('knowledge_document_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['knowledge_documents.tenant_id', 'knowledge_documents.document_id'], name=op.f('fk_knowledge_document_versions_tenant_id_document_id_knowledge_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_document_versions')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'content_hash', name=op.f('uq_knowledge_document_versions_tenant_id_document_id_content_hash')),
    sa.UniqueConstraint('tenant_id', 'version_id', name=op.f('uq_knowledge_document_versions_tenant_id_version_id'))
    )
    op.create_index(op.f('ix_knowledge_document_versions_audience'), 'knowledge_document_versions', ['audience'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_content_hash'), 'knowledge_document_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_document_id'), 'knowledge_document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_language'), 'knowledge_document_versions', ['language'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_status'), 'knowledge_document_versions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_tenant_id'), 'knowledge_document_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_version_id'), 'knowledge_document_versions', ['version_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('redaction_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['conversations.tenant_id', 'conversations.conversation_id'], name=op.f('fk_messages_tenant_id_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('tenant_id', 'message_id', name=op.f('uq_messages_tenant_id_message_id'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('tool_execution_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'run_id'], ['agent_runs.tenant_id', 'agent_runs.run_id'], name=op.f('fk_tool_executions_tenant_id_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_executions')),
    sa.UniqueConstraint('tenant_id', 'tool_execution_id', name=op.f('uq_tool_executions_tenant_id_tool_execution_id'))
    )
    op.create_index(op.f('ix_tool_executions_run_id'), 'tool_executions', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tenant_id'), 'tool_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_execution_id'), 'tool_executions', ['tool_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_tool_execution_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_tenant_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_run_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_document_versions_version_id'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_tenant_id'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_status'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_language'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_document_id'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_content_hash'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_audience'), table_name='knowledge_document_versions')
    op.drop_table('knowledge_document_versions')
    op.drop_index(op.f('ix_agent_runs_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_support_tickets_ticket_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_tenant_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_knowledge_sync_jobs_tenant_id'), table_name='knowledge_sync_jobs')
    op.drop_index(op.f('ix_knowledge_sync_jobs_sync_job_id'), table_name='knowledge_sync_jobs')
    op.drop_index(op.f('ix_knowledge_sync_jobs_status'), table_name='knowledge_sync_jobs')
    op.drop_table('knowledge_sync_jobs')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_conflicts_tenant_id'), table_name='knowledge_conflicts')
    op.drop_index(op.f('ix_knowledge_conflicts_status'), table_name='knowledge_conflicts')
    op.drop_index(op.f('ix_knowledge_conflicts_conflict_id'), table_name='knowledge_conflicts')
    op.drop_table('knowledge_conflicts')
    op.drop_index(op.f('ix_handoff_requests_trace_id'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_tenant_id'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_status'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_reason_code'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_handoff_id'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_customer_id'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_created_at'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_conversation_id'), table_name='handoff_requests')
    op.drop_table('handoff_requests')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_events_trace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###